apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: '2019-05-11T18:33:20Z'
  labels:
    app: messageservice
  name: messageservice
  namespace: dotmastery
  resourceVersion: '361223029'
  selfLink: /api/v1/namespaces/dotmastery/services/messageservice
  uid: 407c0b73-741b-11e9-bbf4-0601fd422288
spec:
  clusterIP: 172.30.228.100
  ports:
    - name: 12345-tcp
      port: 12345
      protocol: TCP
      targetPort: 12345
  selector:
    deploymentconfig: messageservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
