apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: '2019-05-11T18:30:58Z'
  labels:
    app: userservice
  name: userservice
  namespace: dotmastery
  resourceVersion: '361221760'
  selfLink: /api/v1/namespaces/dotmastery/services/userservice
  uid: eba0e22b-741a-11e9-bbf4-0601fd422288
spec:
  clusterIP: 172.30.80.95
  ports:
    - name: 7000-tcp
      port: 7000
      protocol: TCP
      targetPort: 7000
  selector:
    deploymentconfig: userservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
