apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: 'true'
  creationTimestamp: '2019-05-11T18:35:06Z'
  labels:
    app: messageservice
  name: messageservice
  namespace: dotmastery
  resourceVersion: '361223904'
  selfLink: /apis/route.openshift.io/v1/namespaces/dotmastery/routes/messageservice
  uid: 7fd49198-741b-11e9-bbf4-0601fd422288
spec:
  host: messageservice-dotmastery.1d35.starter-us-east-1.openshiftapps.com
  port:
    targetPort: 12345-tcp
  to:
    kind: Service
    name: messageservice
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - lastTransitionTime: '2019-05-11T18:35:06Z'
          status: 'True'
          type: Admitted
      host: messageservice-dotmastery.1d35.starter-us-east-1.openshiftapps.com
      routerCanonicalHostname: elb.e4ff.pro-eu-west-1.openshiftapps.com
      routerName: router
      wildcardPolicy: None
