apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: 'true'
  creationTimestamp: '2019-05-28T20:38:11Z'
  labels:
    app: messageservice
  name: messageservice2
  namespace: dotmastery
  resourceVersion: '373337761'
  selfLink: /apis/route.openshift.io/v1/namespaces/dotmastery/routes/messageservice2
  uid: 82650df4-8188-11e9-ab77-0601fd422288
spec:
  host: messageservice2-dotmastery.e4ff.pro-eu-west-1.openshiftapps.com
  port:
    targetPort: 12345-tcp
  to:
    kind: Service
    name: messageservice
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - lastTransitionTime: '2019-05-28T20:38:11Z'
          status: 'True'
          type: Admitted
      host: messageservice2-dotmastery.e4ff.pro-eu-west-1.openshiftapps.com
      routerCanonicalHostname: elb.e4ff.pro-eu-west-1.openshiftapps.com
      routerName: router
      wildcardPolicy: None
