apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: 'true'
  creationTimestamp: '2019-05-11T19:02:20Z'
  labels:
    app: userservice
  name: userservice
  namespace: dotmastery
  resourceVersion: '361236812'
  selfLink: /apis/route.openshift.io/v1/namespaces/dotmastery/routes/userservice
  uid: 4dc07701-741f-11e9-91c0-0645a759894e
spec:
  host: userservice-dotmastery.e4ff.pro-eu-west-1.openshiftapps.com
  port:
    targetPort: 7000-tcp
  to:
    kind: Service
    name: userservice
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - lastTransitionTime: '2019-05-11T19:02:20Z'
          status: 'True'
          type: Admitted
      host: userservice-dotmastery.e4ff.pro-eu-west-1.openshiftapps.com
      routerCanonicalHostname: elb.e4ff.pro-eu-west-1.openshiftapps.com
      routerName: router
      wildcardPolicy: None
